# Configuration Home Assistant minimale pour le développement local
# Cette instance HA tourne dans le DevContainer

default_config:

# Expose notre custom component
logger:
  default: info
  logs:
    custom_components.smartpoolfiltmgr: info

# Entités fictives pour tester sans vrai matériel
template:
  - sensor:
      - name: "Temperature Piscine (simulée)"
        state: "{{ states('input_number.pool_temperature_sim2') }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Temperature Ballon ECS (simulée)"
        state: "{{ states('input_number.pool_ballon_sim2') }}"
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Production Solaire (simulée)"
        state: "{{ states('input_number.solar_production_sim2') }}"
        unit_of_measurement: "W"
        device_class: power

      - name: "Consommation Réseau (simulée)"
        state: "{{ states('input_number.grid_consumption_sim2') }}"
        unit_of_measurement: "W"
        device_class: power

  - switch:
      - name: "Pompe Piscine (simulée)"
        state: "{{ states('input_boolean.pompe_piscine_sim') }}"
        turn_on:
          service: input_boolean.turn_on
          target:
            entity_id: input_boolean.pompe_piscine_sim
        turn_off:
          service: input_boolean.turn_off
          target:
            entity_id: input_boolean.pompe_piscine_sim

input_boolean:
  pompe_piscine_sim:
    name: "État pompe piscine (sim)"
    initial: false


input_number:
  pool_temperature_sim2:
    name: "Température de la piscine (simulée)"
    initial: 28
    min: 10
    max: 35
    step: 1
  pool_ballon_sim2:
    name: "Température du ballon ECS (simulée)"
    initial: 50
    min: 30
    max: 70
    step: 1
  solar_production_sim2:
    name: "Puissance production solaire simulée"
    initial: 2500
    min: 0
    max: 3000
    step: 100
  grid_consumption_sim2:
    name: "Consommation réseau simulée"
    initial: 500
    min: -2000
    max: 2000
    step: 100
